[build]
  # Publikasikan file dari root folder (tempat index.html berada)
  publish = "./" 

[functions]
  # Fungsi ada di folder netlify/functions (relatif dari root)
  directory = "netlify/functions"

# Tambahkan plugin untuk instalasi dependency
[[plugins]]
  package = "@netlify/plugin-functions-install-core"