[build]
  # Direktori ini harus disetel ke tempat kode front-end Anda (root folder)
  publish = "frontend/" 

[functions]
  # Direktori tempat Netlify akan menemukan fungsi dan package.json
  directory = "frontend/netlify/functions"

[build.environment]
  # Ini adalah perintah yang memaksa Netlify untuk menginstal dependensi di folder functions
  NPM_FLAGS = "--prefix frontend/netlify/functions"